spring:
  data:
    mongo:
      uri: mongodb://localhost:27017/coderhouse
  profiles:
    active: dev
  cache: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeOfLife: 60000
  security:
    user:
      name: coderhouse
      password: 123
jwt:
  expiration: 600000
  secret: springbootjwtcoderhouse

management:
  endpoints:
    web:
      exposure:
        include: refresh
